/**
 * Curated CVE snapshot for DecodeMind's dependency scanner.
 *
 * DecodeMind promises "zero network" — source code never leaves the browser,
 * so we cannot call the OSV.dev API at scan time. Instead this file bundles
 * a hand-picked snapshot of high-impact, well-known CVEs in popular libraries
 * across npm, PyPI, Composer, Go and Cargo ecosystems.
 *
 * Future V3 may add an opt-in "update vulnerability DB" feature that fetches a
 * fresh snapshot. For now, this list is a frozen, vetted starting set. Every
 * entry is sourced from the OSV.dev / GitHub Advisory databases.
 *
 * vulnerableRange uses the same minimal grammar implemented by
 * `semverCompare.ts` — operators (`<`, `<=`, `>`, `>=`, `=`, `==`) joined with
 * `,` mean AND. Examples:
 *   "<4.17.21"          — any version strictly below 4.17.21
 *   ">=2.0.0,<2.1.5"    — 2.0.0 ≤ version < 2.1.5
 */

export type OsvEcosystem = 'npm' | 'pypi' | 'packagist' | 'go' | 'cargo';

export interface OsvCve {
  id: string;             // canonical CVE identifier, e.g. "CVE-2021-23337"
  ecosystem: OsvEcosystem;
  package: string;        // ecosystem-native package name
  vulnerableRange: string;
  severity: 'error' | 'warning' | 'info';
  summary: string;        // one-line human description
  fixVersion: string;     // recommended upgrade target
}

export const OSV_DB: OsvCve[] = [
  // ─── npm / yarn ─────────────────────────────────────────────────────────────
  {
    id: 'CVE-2021-23337',
    ecosystem: 'npm',
    package: 'lodash',
    vulnerableRange: '<4.17.21',
    severity: 'error',
    summary: 'Command injection via template — attacker-controlled template strings reach Function()',
    fixVersion: '4.17.21',
  },
  {
    id: 'CVE-2019-10744',
    ecosystem: 'npm',
    package: 'lodash',
    vulnerableRange: '<4.17.12',
    severity: 'error',
    summary: 'Prototype pollution in defaultsDeep — attacker-controlled property names can poison Object.prototype',
    fixVersion: '4.17.12',
  },
  {
    id: 'CVE-2021-44906',
    ecosystem: 'npm',
    package: 'minimist',
    vulnerableRange: '<1.2.6',
    severity: 'error',
    summary: 'Prototype pollution via --__proto__.x style argv keys',
    fixVersion: '1.2.6',
  },
  {
    id: 'CVE-2022-0235',
    ecosystem: 'npm',
    package: 'node-fetch',
    vulnerableRange: '<2.6.7',
    severity: 'warning',
    summary: 'Exposure of sensitive information — Authorization/Cookie headers forwarded across cross-origin redirects',
    fixVersion: '2.6.7',
  },
  {
    id: 'CVE-2022-0235',
    ecosystem: 'npm',
    package: 'node-fetch',
    vulnerableRange: '>=3.0.0,<3.1.1',
    severity: 'warning',
    summary: 'Exposure of sensitive information — Authorization/Cookie headers forwarded across cross-origin redirects',
    fixVersion: '3.1.1',
  },
  {
    id: 'CVE-2021-3749',
    ecosystem: 'npm',
    package: 'axios',
    vulnerableRange: '<0.21.2',
    severity: 'error',
    summary: 'ReDoS / SSRF in trim — regex used to parse upload destination is catastrophically backtracky',
    fixVersion: '0.21.2',
  },
  {
    id: 'CVE-2023-45857',
    ecosystem: 'npm',
    package: 'axios',
    vulnerableRange: '>=0.8.1,<1.6.0',
    severity: 'warning',
    summary: 'CSRF token leak — XSRF-TOKEN cookie sent to cross-origin URLs',
    fixVersion: '1.6.0',
  },
  {
    id: 'CVE-2022-29078',
    ecosystem: 'npm',
    package: 'ejs',
    vulnerableRange: '<3.1.7',
    severity: 'error',
    summary: 'Server-side template injection — attacker-controlled options.outputFunctionName leads to RCE',
    fixVersion: '3.1.7',
  },
  {
    id: 'CVE-2020-7660',
    ecosystem: 'npm',
    package: 'serialize-javascript',
    vulnerableRange: '<3.1.0',
    severity: 'error',
    summary: 'XSS via regex escape — attacker-supplied regex in input bypasses sanitization',
    fixVersion: '3.1.0',
  },
  {
    id: 'CVE-2021-32640',
    ecosystem: 'npm',
    package: 'ws',
    vulnerableRange: '<7.4.6',
    severity: 'warning',
    summary: 'ReDoS in Sec-Websocket-Protocol header parser',
    fixVersion: '7.4.6',
  },
  {
    id: 'CVE-2023-26159',
    ecosystem: 'npm',
    package: 'follow-redirects',
    vulnerableRange: '<1.15.4',
    severity: 'warning',
    summary: 'Improper input validation — Authorization header leaks to cross-origin redirect target',
    fixVersion: '1.15.4',
  },
  {
    id: 'CVE-2023-46298',
    ecosystem: 'npm',
    package: 'next',
    vulnerableRange: '>=13.4.0,<13.5.1',
    severity: 'warning',
    summary: 'Cache poisoning — missing cache key validation in image optimization route',
    fixVersion: '13.5.1',
  },
  {
    id: 'CVE-2024-34351',
    ecosystem: 'npm',
    package: 'next',
    vulnerableRange: '>=13.4.0,<14.1.1',
    severity: 'error',
    summary: 'Server-side request forgery via Host header in Server Actions redirect handling',
    fixVersion: '14.1.1',
  },
  {
    id: 'GHSA-67hx-6x53-jw92',
    ecosystem: 'npm',
    package: 'json5',
    vulnerableRange: '<1.0.2',
    severity: 'error',
    summary: 'Prototype pollution via parse — __proto__ key in JSON5 input poisons Object.prototype',
    fixVersion: '1.0.2',
  },
  {
    id: 'GHSA-67hx-6x53-jw92',
    ecosystem: 'npm',
    package: 'json5',
    vulnerableRange: '>=2.0.0,<2.2.2',
    severity: 'error',
    summary: 'Prototype pollution via parse — __proto__ key in JSON5 input poisons Object.prototype',
    fixVersion: '2.2.2',
  },
  {
    id: 'CVE-2022-24999',
    ecosystem: 'npm',
    package: 'express',
    vulnerableRange: '<4.17.3',
    severity: 'warning',
    summary: 'Prototype pollution via qs nested object parsing — affects Express ≤4.17.2',
    fixVersion: '4.17.3',
  },
  {
    id: 'CVE-2024-29415',
    ecosystem: 'npm',
    package: 'ip',
    vulnerableRange: '<2.0.1',
    severity: 'error',
    summary: 'SSRF — isPublic() incorrectly classifies certain IPv4-mapped IPv6 addresses as public',
    fixVersion: '2.0.1',
  },
  {
    id: 'CVE-2022-25883',
    ecosystem: 'npm',
    package: 'semver',
    vulnerableRange: '<5.7.2',
    severity: 'warning',
    summary: 'ReDoS in new Range() — crafted version range causes exponential backtracking',
    fixVersion: '5.7.2',
  },
  {
    id: 'CVE-2022-25883',
    ecosystem: 'npm',
    package: 'semver',
    vulnerableRange: '>=6.0.0,<6.3.1',
    severity: 'warning',
    summary: 'ReDoS in new Range() — crafted version range causes exponential backtracking',
    fixVersion: '6.3.1',
  },
  {
    id: 'CVE-2022-25883',
    ecosystem: 'npm',
    package: 'semver',
    vulnerableRange: '>=7.0.0,<7.5.2',
    severity: 'warning',
    summary: 'ReDoS in new Range() — crafted version range causes exponential backtracking',
    fixVersion: '7.5.2',
  },
  {
    id: 'CVE-2024-28849',
    ecosystem: 'npm',
    package: 'follow-redirects',
    vulnerableRange: '<1.15.6',
    severity: 'warning',
    summary: 'Proxy-Authorization header leaks to cross-origin redirect target',
    fixVersion: '1.15.6',
  },
  {
    id: 'CVE-2024-21484',
    ecosystem: 'npm',
    package: 'jsrsasign',
    vulnerableRange: '<11.0.0',
    severity: 'error',
    summary: 'JWT signature validation bypass — null algorithm accepted as valid',
    fixVersion: '11.0.0',
  },
  {
    id: 'CVE-2024-21538',
    ecosystem: 'npm',
    package: 'cross-spawn',
    vulnerableRange: '<6.0.6',
    severity: 'warning',
    summary: 'ReDoS via crafted command argument',
    fixVersion: '6.0.6',
  },

  // ─── pip / PyPI ─────────────────────────────────────────────────────────────
  {
    id: 'CVE-2022-22817',
    ecosystem: 'pypi',
    package: 'pillow',
    vulnerableRange: '<9.0.0',
    severity: 'error',
    summary: 'Arbitrary code execution via PIL.ImageMath.eval — attacker-controlled environment expression',
    fixVersion: '9.0.1',
  },
  {
    id: 'CVE-2023-44271',
    ecosystem: 'pypi',
    package: 'pillow',
    vulnerableRange: '<10.0.1',
    severity: 'error',
    summary: 'Heap buffer overflow / DoS in ImageFont rendering for non-TrueType fonts',
    fixVersion: '10.0.1',
  },
  {
    id: 'CVE-2018-18074',
    ecosystem: 'pypi',
    package: 'requests',
    vulnerableRange: '<2.20.0',
    severity: 'warning',
    summary: 'Authorization header forwarded to cross-origin redirect target',
    fixVersion: '2.20.0',
  },
  {
    id: 'CVE-2024-35195',
    ecosystem: 'pypi',
    package: 'requests',
    vulnerableRange: '<2.32.0',
    severity: 'warning',
    summary: 'verify=False on first request persists for subsequent calls in same Session',
    fixVersion: '2.32.0',
  },
  {
    id: 'CVE-2023-23969',
    ecosystem: 'pypi',
    package: 'django',
    vulnerableRange: '<3.2.18',
    severity: 'warning',
    summary: 'DoS — Accept-Language header parsing allowed crafted long strings',
    fixVersion: '3.2.18',
  },
  {
    id: 'CVE-2023-23969',
    ecosystem: 'pypi',
    package: 'django',
    vulnerableRange: '>=4.0.0,<4.0.10',
    severity: 'warning',
    summary: 'DoS — Accept-Language header parsing allowed crafted long strings',
    fixVersion: '4.0.10',
  },
  {
    id: 'CVE-2023-23969',
    ecosystem: 'pypi',
    package: 'django',
    vulnerableRange: '>=4.1.0,<4.1.7',
    severity: 'warning',
    summary: 'DoS — Accept-Language header parsing allowed crafted long strings',
    fixVersion: '4.1.7',
  },
  {
    id: 'CVE-2023-46695',
    ecosystem: 'pypi',
    package: 'django',
    vulnerableRange: '>=4.2.0,<4.2.7',
    severity: 'warning',
    summary: 'DoS in UsernameField — crafted long usernames cause excessive NFKC normalization',
    fixVersion: '4.2.7',
  },
  {
    id: 'CVE-2023-30861',
    ecosystem: 'pypi',
    package: 'flask',
    vulnerableRange: '<2.2.5',
    severity: 'error',
    summary: 'Cookie/session leak across users when proxy caches cookies; missing Vary: Cookie',
    fixVersion: '2.2.5',
  },
  {
    id: 'CVE-2023-30861',
    ecosystem: 'pypi',
    package: 'flask',
    vulnerableRange: '>=2.3.0,<2.3.2',
    severity: 'error',
    summary: 'Cookie/session leak across users when proxy caches cookies; missing Vary: Cookie',
    fixVersion: '2.3.2',
  },
  {
    id: 'CVE-2023-23931',
    ecosystem: 'pypi',
    package: 'cryptography',
    vulnerableRange: '<39.0.1',
    severity: 'warning',
    summary: 'Cipher.update_into() accepts immutable buffers — silent corruption rather than error',
    fixVersion: '39.0.1',
  },
  {
    id: 'CVE-2020-14343',
    ecosystem: 'pypi',
    package: 'pyyaml',
    vulnerableRange: '<5.4',
    severity: 'error',
    summary: 'Arbitrary code execution via yaml.full_load on untrusted input — sub-class chain bypass',
    fixVersion: '5.4',
  },
  {
    id: 'CVE-2023-45803',
    ecosystem: 'pypi',
    package: 'urllib3',
    vulnerableRange: '<1.26.18',
    severity: 'warning',
    summary: 'Request body not stripped on cross-host 303 redirect (potential auth/data leak)',
    fixVersion: '1.26.18',
  },
  {
    id: 'CVE-2023-45803',
    ecosystem: 'pypi',
    package: 'urllib3',
    vulnerableRange: '>=2.0.0,<2.0.7',
    severity: 'warning',
    summary: 'Request body not stripped on cross-host 303 redirect (potential auth/data leak)',
    fixVersion: '2.0.7',
  },
  {
    id: 'CVE-2024-1135',
    ecosystem: 'pypi',
    package: 'gunicorn',
    vulnerableRange: '<22.0.0',
    severity: 'error',
    summary: 'HTTP request smuggling via crafted Transfer-Encoding header parsing',
    fixVersion: '22.0.0',
  },
  {
    id: 'CVE-2024-34069',
    ecosystem: 'pypi',
    package: 'werkzeug',
    vulnerableRange: '<3.0.3',
    severity: 'error',
    summary: 'Debugger RCE — PIN bypass on dev server allows arbitrary code execution',
    fixVersion: '3.0.3',
  },
  {
    id: 'CVE-2023-25577',
    ecosystem: 'pypi',
    package: 'werkzeug',
    vulnerableRange: '<2.2.3',
    severity: 'warning',
    summary: 'DoS via multipart parsing — unbounded memory allocation on crafted forms',
    fixVersion: '2.2.3',
  },
  {
    id: 'CVE-2024-3651',
    ecosystem: 'pypi',
    package: 'idna',
    vulnerableRange: '<3.7',
    severity: 'warning',
    summary: 'Quadratic-complexity DoS in idna.encode() for crafted very-long labels',
    fixVersion: '3.7',
  },
  {
    id: 'CVE-2024-3772',
    ecosystem: 'pypi',
    package: 'pydantic',
    vulnerableRange: '<1.10.13',
    severity: 'warning',
    summary: 'ReDoS via crafted regex constraint',
    fixVersion: '1.10.13',
  },
  {
    id: 'CVE-2024-3772',
    ecosystem: 'pypi',
    package: 'pydantic',
    vulnerableRange: '>=2.0.0,<2.4.0',
    severity: 'warning',
    summary: 'ReDoS via crafted regex constraint',
    fixVersion: '2.4.0',
  },
  {
    id: 'CVE-2024-1727',
    ecosystem: 'pypi',
    package: 'fastapi',
    vulnerableRange: '<0.109.1',
    severity: 'warning',
    summary: 'ReDoS in form/multipart parsing on Content-Type boundary header',
    fixVersion: '0.109.1',
  },

  // ─── Composer / Packagist ───────────────────────────────────────────────────
  {
    id: 'CVE-2024-28861',
    ecosystem: 'packagist',
    package: 'symfony/http-foundation',
    vulnerableRange: '<4.4.51',
    severity: 'warning',
    summary: 'Session fixation — session id not regenerated on login when using native session storage',
    fixVersion: '4.4.51',
  },
  {
    id: 'CVE-2024-28861',
    ecosystem: 'packagist',
    package: 'symfony/http-foundation',
    vulnerableRange: '>=5.0.0,<5.4.35',
    severity: 'warning',
    summary: 'Session fixation — session id not regenerated on login when using native session storage',
    fixVersion: '5.4.35',
  },
  {
    id: 'CVE-2021-43808',
    ecosystem: 'packagist',
    package: 'laravel/framework',
    vulnerableRange: '>=8.0.0,<8.75.0',
    severity: 'error',
    summary: 'XSS in Blade — attacker-controlled component prop bypasses HTML escaping',
    fixVersion: '8.75.0',
  },
  {
    id: 'CVE-2024-29291',
    ecosystem: 'packagist',
    package: 'laravel/framework',
    vulnerableRange: '>=9.0.0,<10.46.0',
    severity: 'warning',
    summary: 'Disclosure of database credentials via debug page when APP_DEBUG=true',
    fixVersion: '10.46.0',
  },
  {
    id: 'CVE-2023-29197',
    ecosystem: 'packagist',
    package: 'guzzlehttp/psr7',
    vulnerableRange: '<2.4.5',
    severity: 'warning',
    summary: 'Improper input validation — invalid header characters accepted by HTTP message parser',
    fixVersion: '2.4.5',
  },
  {
    id: 'CVE-2023-29197',
    ecosystem: 'packagist',
    package: 'guzzlehttp/psr7',
    vulnerableRange: '>=1.0.0,<1.9.1',
    severity: 'warning',
    summary: 'Improper input validation — invalid header characters accepted by HTTP message parser',
    fixVersion: '1.9.1',
  },
  {
    id: 'CVE-2022-31091',
    ecosystem: 'packagist',
    package: 'guzzlehttp/guzzle',
    vulnerableRange: '>=7.0.0,<7.4.5',
    severity: 'warning',
    summary: 'Cross-domain header propagation — Authorization/Cookie forwarded across origins on redirect',
    fixVersion: '7.4.5',
  },

  // ─── Go modules ─────────────────────────────────────────────────────────────
  {
    id: 'CVE-2023-29401',
    ecosystem: 'go',
    package: 'github.com/gin-gonic/gin',
    vulnerableRange: '<1.9.1',
    severity: 'warning',
    summary: 'Open redirect via Content-Disposition header — unsanitized filename in attachment response',
    fixVersion: '1.9.1',
  },
  {
    id: 'CVE-2023-44487',
    ecosystem: 'go',
    package: 'golang.org/x/net',
    vulnerableRange: '<0.17.0',
    severity: 'error',
    summary: 'HTTP/2 Rapid Reset DoS — stream cancellation amplification (CVE-2023-44487)',
    fixVersion: '0.17.0',
  },
  {
    id: 'CVE-2023-39325',
    ecosystem: 'go',
    package: 'golang.org/x/net',
    vulnerableRange: '<0.17.0',
    severity: 'error',
    summary: 'HTTP/2 stream reset DoS — same Rapid Reset family',
    fixVersion: '0.17.0',
  },
  {
    id: 'CVE-2024-24786',
    ecosystem: 'go',
    package: 'google.golang.org/protobuf',
    vulnerableRange: '<1.33.0',
    severity: 'warning',
    summary: 'Infinite loop in protojson unmarshalling on malformed input',
    fixVersion: '1.33.0',
  },
  {
    id: 'CVE-2023-49568',
    ecosystem: 'go',
    package: 'github.com/go-git/go-git/v5',
    vulnerableRange: '<5.11.0',
    severity: 'warning',
    summary: 'DoS in pack file parsing — unbounded memory allocation on crafted Git pack',
    fixVersion: '5.11.0',
  },
  {
    id: 'CVE-2023-39533',
    ecosystem: 'go',
    package: 'github.com/jackc/pgx/v4',
    vulnerableRange: '<4.18.2',
    severity: 'warning',
    summary: 'SQL injection — unsanitized identifier when using SimpleProtocol with text-format args',
    fixVersion: '4.18.2',
  },

  // ─── Rust / Cargo ───────────────────────────────────────────────────────────
  {
    id: 'RUSTSEC-2020-0159',
    ecosystem: 'cargo',
    package: 'chrono',
    vulnerableRange: '<0.4.20',
    severity: 'info',
    summary: 'Soundness — uses outdated time crate vulnerable to segfault on Windows for certain inputs',
    fixVersion: '0.4.20',
  },
  {
    id: 'RUSTSEC-2024-0019',
    ecosystem: 'cargo',
    package: 'mio',
    vulnerableRange: '<0.8.11',
    severity: 'warning',
    summary: 'Token reuse after Registry drop — use-after-free in IO source teardown on Windows',
    fixVersion: '0.8.11',
  },
  {
    id: 'CVE-2024-32650',
    ecosystem: 'cargo',
    package: 'rustls',
    vulnerableRange: '<0.21.11',
    severity: 'warning',
    summary: 'DoS via fatal alert before handshake completion causes panic in some configurations',
    fixVersion: '0.21.11',
  },
  {
    id: 'RUSTSEC-2022-0093',
    ecosystem: 'cargo',
    package: 'openssl',
    vulnerableRange: '<0.10.55',
    severity: 'warning',
    summary: 'Use-after-free in MemBio implementation on certain error paths',
    fixVersion: '0.10.55',
  },
  {
    id: 'CVE-2024-27308',
    ecosystem: 'cargo',
    package: 'mio',
    vulnerableRange: '>=0.7.0,<0.7.14',
    severity: 'warning',
    summary: 'Windows named-pipe handles closed twice — potential use-after-close on stale handle',
    fixVersion: '0.7.14',
  },
];
