import { describe, it, expect } from 'vitest';
import {
  IGNORED_DIRS,
  AUTO_GENERATED_HEADERS,
  EXT_TO_SCANNER,
  MAX_FILES,
  MAX_FILE_BYTES,
} from '@/spike/folderScan';

// ─── IGNORED_DIRS ─────────────────────────────────────────────────────────────

describe('IGNORED_DIRS', () => {
  it('contains node_modules', () => {
    expect(IGNORED_DIRS.has('node_modules')).toBe(true);
  });

  it('contains vendor', () => {
    expect(IGNORED_DIRS.has('vendor')).toBe(true);
  });

  it('contains third_party', () => {
    expect(IGNORED_DIRS.has('third_party')).toBe(true);
  });

  it('contains whisper-cpp', () => {
    expect(IGNORED_DIRS.has('whisper-cpp')).toBe(true);
  });

  it('contains .git', () => {
    expect(IGNORED_DIRS.has('.git')).toBe(true);
  });

  it('contains dist', () => {
    expect(IGNORED_DIRS.has('dist')).toBe(true);
  });

  it('contains __pycache__', () => {
    expect(IGNORED_DIRS.has('__pycache__')).toBe(true);
  });

  it('does not contain src (user code must be included)', () => {
    expect(IGNORED_DIRS.has('src')).toBe(false);
  });
});

// ─── AUTO_GENERATED_HEADERS ───────────────────────────────────────────────────

describe('AUTO_GENERATED_HEADERS', () => {
  it('is a non-empty array', () => {
    expect(Array.isArray(AUTO_GENERATED_HEADERS)).toBe(true);
    expect(AUTO_GENERATED_HEADERS.length).toBeGreaterThan(0);
  });

  it('contains "# Auto-generated"', () => {
    expect(AUTO_GENERATED_HEADERS).toContain('# Auto-generated');
  });

  it('contains "// Auto-generated"', () => {
    expect(AUTO_GENERATED_HEADERS).toContain('// Auto-generated');
  });

  it('contains "# DO NOT EDIT"', () => {
    expect(AUTO_GENERATED_HEADERS).toContain('# DO NOT EDIT');
  });

  it('contains "// DO NOT EDIT"', () => {
    expect(AUTO_GENERATED_HEADERS).toContain('// DO NOT EDIT');
  });

  it('contains "# Generated by"', () => {
    expect(AUTO_GENERATED_HEADERS).toContain('# Generated by');
  });

  it('contains "// Generated by"', () => {
    expect(AUTO_GENERATED_HEADERS).toContain('// Generated by');
  });

  it('contains "// AUTO-GENERATED"', () => {
    expect(AUTO_GENERATED_HEADERS).toContain('// AUTO-GENERATED');
  });
});

// ─── EXT_TO_SCANNER ───────────────────────────────────────────────────────────

describe('EXT_TO_SCANNER', () => {
  it('maps .py to ruff', () => {
    expect(EXT_TO_SCANNER['.py']).toBe('ruff');
  });

  it('maps .ts to eslint', () => {
    expect(EXT_TO_SCANNER['.ts']).toBe('eslint');
  });

  it('maps .tsx to eslint', () => {
    expect(EXT_TO_SCANNER['.tsx']).toBe('eslint');
  });

  it('maps .js to eslint', () => {
    expect(EXT_TO_SCANNER['.js']).toBe('eslint');
  });

  it('maps .jsx to eslint', () => {
    expect(EXT_TO_SCANNER['.jsx']).toBe('eslint');
  });

  it('maps .mjs to eslint', () => {
    expect(EXT_TO_SCANNER['.mjs']).toBe('eslint');
  });

  it('maps .cjs to eslint', () => {
    expect(EXT_TO_SCANNER['.cjs']).toBe('eslint');
  });

  it('maps .html to prettier-html', () => {
    expect(EXT_TO_SCANNER['.html']).toBe('prettier-html');
  });

  it('maps .htm to prettier-html', () => {
    expect(EXT_TO_SCANNER['.htm']).toBe('prettier-html');
  });

  it('maps .css to prettier-css', () => {
    expect(EXT_TO_SCANNER['.css']).toBe('prettier-css');
  });

  it('maps .scss to prettier-css', () => {
    expect(EXT_TO_SCANNER['.scss']).toBe('prettier-css');
  });

  it('does not map .txt (unsupported extension)', () => {
    expect(EXT_TO_SCANNER['.txt']).toBeUndefined();
  });
});

// ─── Constants sanity ─────────────────────────────────────────────────────────

describe('MAX_FILES and MAX_FILE_BYTES', () => {
  it('MAX_FILES is 500', () => {
    expect(MAX_FILES).toBe(500);
  });

  it('MAX_FILE_BYTES is 1MB', () => {
    expect(MAX_FILE_BYTES).toBe(1_000_000);
  });
});
