import ignore from 'ignore';
import type { RuffResponse } from '@/workers/ruff.worker';
import type { EslintResponse } from '@/workers/eslint.worker';
import type { PrettierResponse } from '@/workers/prettier.worker';
import type { NormalizedEdit } from '@/lib/fixes/applyEdit';
import { ruffFixToEdits } from '@/lib/fixes/convertRuffFix';
import { eslintFixToEdits } from '@/lib/fixes/convertEslintFix';

// ─── Constants ───────────────────────────────────────────────────────────────

export const IGNORED_DIRS = new Set([
  // Generated / build output
  'node_modules', '.git', 'dist', 'build', '.next', '.vite', '.turbo',
  'coverage', 'out', 'target', 'bin', 'obj',
  // Python
  'venv', '.venv', 'env', '.env-dir', '__pycache__', '.pytest_cache', '.mypy_cache', '.ruff_cache',
  // Editors / tooling
  '.vscode', '.idea', '.cache', '.parcel-cache', '.decodemind-backup',
  // Vendored third-party code (commonly contains noise that isn't the user's to fix)
  'vendor', 'vendors', 'third_party', 'third-party', 'thirdparty',
  'external', 'externals', 'deps', 'ext', 'libs',
  // Common ML / native libs that get vendored into projects
  'whisper-cpp', 'llama-cpp', 'ggml', 'onnxruntime', 'tensorflow-lite',
]);

// Also skip files starting with these auto-generated markers (heuristic).
// V1 should make this configurable via a `.decodemind-ignore` project file.
export const AUTO_GENERATED_HEADERS = [
  '# Auto-generated',
  '# AUTO-GENERATED',
  '// Auto-generated',
  '// AUTO-GENERATED',
  '/* Auto-generated',
  '<!-- Auto-generated',
  '# Generated by',
  '// Generated by',
  '# DO NOT EDIT',
  '// DO NOT EDIT',
];

export const MAX_FILES = 500;
export const MAX_FILE_BYTES = 1_000_000;

// ─── Types ───────────────────────────────────────────────────────────────────

export type ScannerKind = 'ruff' | 'eslint' | 'prettier-html' | 'prettier-css';

export const EXT_TO_SCANNER: Record<string, ScannerKind> = {
  '.py': 'ruff',
  '.ts': 'eslint', '.tsx': 'eslint', '.js': 'eslint', '.jsx': 'eslint',
  '.mjs': 'eslint', '.cjs': 'eslint',
  '.html': 'prettier-html', '.htm': 'prettier-html',
  '.css': 'prettier-css', '.scss': 'prettier-css',
};

export interface ScanFile {
  path: string;      // posix-style relative path from the picked root
  content: string;
  scanner: ScannerKind;
}

export interface AggregatedFinding {
  file: string;
  line: number | null;
  severity: 'error' | 'warning' | 'info';
  ruleId: string | null;
  message: string;
  edits?: NormalizedEdit[];  // present when the scanner provided a fix
}

export interface FolderScanReport {
  filesScanned: number;
  filesSkipped: number;   // oversized files we read but skipped
  totalFiles: number;     // all matched files before MAX_FILES cap
  findings: AggregatedFinding[];
  elapsedMs: number;
  warnings: string[];
}

// ─── .decodemind-ignore support ───────────────────────────────────────────────

/**
 * Try to read `.decodemind-ignore` from the root directory.
 * Returns its text content, or null if the file doesn't exist.
 */
export async function readIgnoreFile(
  root: FileSystemDirectoryHandle,
): Promise<string | null> {
  try {
    const fileHandle = await root.getFileHandle('.decodemind-ignore');
    const file = await fileHandle.getFile();
    return await file.text();
  } catch (err) {
    // NotFoundError is expected when the file doesn't exist — swallow it.
    // Re-throw anything else (e.g. permission errors).
    if (err instanceof DOMException && err.name === 'NotFoundError') {
      return null;
    }
    throw err;
  }
}

// ─── collectFiles ─────────────────────────────────────────────────────────────

/**
 * Walk a FileSystemDirectoryHandle recursively, returning matched ScanFile[].
 * Respects IGNORED_DIRS, .decodemind-ignore patterns, MAX_FILES, and MAX_FILE_BYTES.
 */
export async function collectFiles(
  root: FileSystemDirectoryHandle,
): Promise<{ files: ScanFile[]; warnings: string[]; totalSeen: number }> {
  const files: ScanFile[] = [];
  const warnings: string[] = [];
  let totalSeen = 0;

  // ── Load .decodemind-ignore if present ──────────────────────────────────────
  const ignoreText = await readIgnoreFile(root);
  let ig: ReturnType<typeof ignore> | null = null;
  if (ignoreText !== null) {
    ig = ignore().add(ignoreText);
    const patternCount = ignoreText
      .split('\n')
      .filter((line) => line.trim() !== '' && !line.trim().startsWith('#'))
      .length;
    warnings.push(`Loaded ${patternCount} patterns from .decodemind-ignore`);
  }

  async function walk(dir: FileSystemDirectoryHandle, prefix: string): Promise<void> {
    // FileSystemDirectoryHandle is async-iterable in browsers but TypeScript's
    // DOM lib only gained this signature in newer versions. Cast to avoid the
    // TS2504 error without requiring DOM.AsyncIterable in tsconfig.lib.
    const iterable = dir as unknown as AsyncIterable<[string, FileSystemHandle]>;
    for await (const [name, handle] of iterable) {
      const relativePath = prefix ? `${prefix}/${name}` : name;

      if (handle.kind === 'directory') {
        if (IGNORED_DIRS.has(name)) continue;
        // Check .decodemind-ignore for directories (append slash for dir matching)
        if (ig && ig.ignores(relativePath)) continue;
        await walk(handle as FileSystemDirectoryHandle, relativePath);
      } else {
        // It's a file — check extension
        const dotIdx = name.lastIndexOf('.');
        if (dotIdx === -1) continue;
        const ext = name.slice(dotIdx).toLowerCase();
        const scanner = EXT_TO_SCANNER[ext];
        if (!scanner) continue;

        // Check .decodemind-ignore for files
        if (ig && ig.ignores(relativePath)) continue;

        totalSeen++;
        if (files.length >= MAX_FILES) continue; // keep counting but don't add

        const fileHandle = handle as FileSystemFileHandle;
        const file = await fileHandle.getFile();

        if (file.size > MAX_FILE_BYTES) {
          warnings.push(`Skipped ${relativePath} (${(file.size / 1_048_576).toFixed(1)} MB > 1 MB limit)`);
          continue;
        }

        const content = await file.text();

        // Heuristic: skip files whose first 200 chars match a known "auto-generated" header.
        const head = content.slice(0, 200);
        const isGenerated = AUTO_GENERATED_HEADERS.some((m) => head.includes(m));
        if (isGenerated) {
          warnings.push(`Skipped ${relativePath} (auto-generated header detected)`);
          continue;
        }

        files.push({ path: relativePath, content, scanner });
      }
    }
  }

  await walk(root, '');

  if (totalSeen > MAX_FILES) {
    warnings.unshift(
      `Folder has ${totalSeen} files, scanning first ${MAX_FILES}. Use ignore list to narrow.`,
    );
  }

  return { files, warnings, totalSeen };
}

// ─── scanAllFiles ─────────────────────────────────────────────────────────────

// Worker URLs must be relative literals — NOT `@/` aliases — for Vite's static
// analyzer to bundle them as separate worker chunks.
function makeRuffWorker() {
  return new Worker(new URL('../workers/ruff.worker.ts', import.meta.url), { type: 'module' });
}
function makeEslintWorker() {
  return new Worker(new URL('../workers/eslint.worker.ts', import.meta.url), { type: 'module' });
}
function makePrettierWorker() {
  return new Worker(new URL('../workers/prettier.worker.ts', import.meta.url), { type: 'module' });
}

/** Send one message to a worker and resolve with the response. */
function ask<TReq, TRes>(worker: Worker, req: TReq): Promise<TRes> {
  return new Promise<TRes>((resolve, reject) => {
    worker.onmessage = (e: MessageEvent<TRes>) => resolve(e.data);
    worker.onerror = (e) => reject(new Error(e.message || 'worker error'));
    worker.onmessageerror = () => reject(new Error('worker messageerror'));
    worker.postMessage(req);
  });
}

/**
 * Map a Ruff rule code to a DecodeMind severity.
 *
 * Ruff doesn't carry a per-finding severity — only a rule code. We derive
 * severity from the code prefix so the report's "Critical / Important / Minor"
 * labels match user intuition. See https://docs.astral.sh/ruff/rules/ for codes.
 */
export function ruffSeverity(code: string | null): AggregatedFinding['severity'] {
  if (!code) return 'warning';
  // Security (bandit-ported S*) — real exposure
  if (code.startsWith('S')) return 'error';
  // Pyflakes F* — undefined names, unused imports, real bugs
  if (code.startsWith('F')) return 'error';
  // Bugbear B*, async ASYNC*, blind-except BLE* — warning-level bugs
  if (code.startsWith('B') || code.startsWith('ASYNC') || code.startsWith('BLE')) return 'warning';
  // Real warnings W*
  if (code.startsWith('W')) return 'warning';
  // Style E*, modernisation UP*, complexity C9*, naming N*, annotations ANN*, isort I*, quote Q* — info
  if (
    code.startsWith('E') ||
    code.startsWith('UP') ||
    code.startsWith('C9') ||
    code.startsWith('N') ||
    code.startsWith('ANN') ||
    code.startsWith('Q') ||
    code.startsWith('I')
  ) {
    return 'info';
  }
  return 'warning';
}

function eslintSeverity(n: number): AggregatedFinding['severity'] {
  if (n === 2) return 'error';
  if (n === 1) return 'warning';
  return 'info';
}

// ─── Worker pool ─────────────────────────────────────────────────────────────

const POOL_SIZE = 2;

/**
 * Run a pool of N workers over a list of jobs.
 * Each worker is created by `makeWorker` and processes one job at a time.
 * Jobs are dispatched as workers become free (available-queue style).
 */
async function runPool<TReq, TRes>(
  makeWorker: () => Worker,
  poolSize: number,
  jobs: Array<{ request: TReq; onResult: (res: TRes) => void }>,
): Promise<void> {
  if (jobs.length === 0) return;

  const actualSize = Math.min(poolSize, jobs.length);
  const workers = Array.from({ length: actualSize }, makeWorker);

  // Track which worker is free: a Promise that resolves when the worker
  // finishes its current task (initially all resolve immediately).
  const workerSlots: Promise<void>[] = workers.map(() => Promise.resolve());

  // A queue index we hand out round-trips; but we actually want "pick the
  // soonest free worker", so we use a Promise.race over the slots.
  let jobIndex = 0;

  // Kick off initial batch: one job per worker
  const inFlight: Array<Promise<void>> = [];

  function dispatchNext(workerIdx: number): Promise<void> {
    if (jobIndex >= jobs.length) return Promise.resolve();
    const job = jobs[jobIndex++];
    const p: Promise<void> = ask<TReq, TRes>(workers[workerIdx], job.request).then(
      (res) => {
        job.onResult(res);
        // Chain: when this slot frees, pick the next job for this worker
        workerSlots[workerIdx] = dispatchNext(workerIdx);
      },
    );
    return p;
  }

  // Seed each worker with its first job
  for (let i = 0; i < actualSize; i++) {
    workerSlots[i] = dispatchNext(i);
    inFlight.push(workerSlots[i]);
  }

  // Wait until all workers have drained
  // Since each slot chains into the next job, we wait for all slots to settle
  await Promise.all(workerSlots);

  // Terminate all workers
  for (const w of workers) w.terminate();
}

/**
 * Run all files through the appropriate workers.
 * Uses a pool of POOL_SIZE workers per scanner kind for parallel processing.
 * onProgress fires after each file completes.
 */
export async function scanAllFiles(
  files: ScanFile[],
  onProgress: (
    done: Record<ScannerKind, number>,
    total: Record<ScannerKind, number>,
  ) => void,
): Promise<FolderScanReport> {
  const start = performance.now();
  const findings: AggregatedFinding[] = [];
  const warnings: string[] = [];

  // Pre-count totals per scanner
  const total: Record<ScannerKind, number> = {
    ruff: 0, eslint: 0, 'prettier-html': 0, 'prettier-css': 0,
  };
  for (const f of files) total[f.scanner]++;

  const done: Record<ScannerKind, number> = {
    ruff: 0, eslint: 0, 'prettier-html': 0, 'prettier-css': 0,
  };

  let filesScanned = 0;
  let filesSkipped = 0;

  // ── Ruff pool ────────────────────────────────────────────────────────────────
  const ruffFiles = files.filter((f) => f.scanner === 'ruff');
  if (ruffFiles.length > 0) {
    type RuffReq = { type: 'scan'; source: string };
    const jobs = ruffFiles.map((file) => ({
      request: { type: 'scan' as const, source: file.content },
      onResult: (res: RuffResponse) => {
        if (res.type === 'error') {
          warnings.push(`Ruff error on ${file.path}: ${res.message}`);
          filesSkipped++;
        } else {
          for (const d of res.diagnostics) {
            const edits = ruffFixToEdits(d);
            findings.push({
              file: file.path,
              line: d.start_location.row,
              severity: ruffSeverity(d.code),
              ruleId: d.code,
              message: d.message,
              ...(edits.length > 0 ? { edits } : {}),
            });
          }
          filesScanned++;
        }
        done.ruff++;
        onProgress({ ...done }, { ...total });
      },
    }));
    await runPool<RuffReq, RuffResponse>(makeRuffWorker, POOL_SIZE, jobs);
  }

  // ── ESLint pool ──────────────────────────────────────────────────────────────
  const eslintFiles = files.filter((f) => f.scanner === 'eslint');
  if (eslintFiles.length > 0) {
    type EslintReq = { type: 'lint'; source: string; filename: string };
    const jobs = eslintFiles.map((file) => ({
      request: { type: 'lint' as const, source: file.content, filename: file.path },
      onResult: (res: EslintResponse) => {
        if (res.type === 'error') {
          warnings.push(`ESLint error on ${file.path}: ${res.message}`);
          filesSkipped++;
        } else {
          for (const m of res.messages) {
            const edits = eslintFixToEdits(m, file.content);
            findings.push({
              file: file.path,
              line: m.line ?? null,
              severity: eslintSeverity(m.severity),
              ruleId: m.ruleId,
              message: m.message,
              ...(edits.length > 0 ? { edits } : {}),
            });
          }
          filesScanned++;
        }
        done.eslint++;
        onProgress({ ...done }, { ...total });
      },
    }));
    await runPool<EslintReq, EslintResponse>(makeEslintWorker, POOL_SIZE, jobs);
  }

  // ── Prettier pool (html + css share one pool) ─────────────────────────────────
  const prettierFiles = files.filter(
    (f) => f.scanner === 'prettier-html' || f.scanner === 'prettier-css',
  );
  if (prettierFiles.length > 0) {
    type PrettierReq = { type: 'format'; source: string; parser: 'html' | 'css' };
    const jobs = prettierFiles.map((file) => {
      const parser = file.scanner === 'prettier-html' ? 'html' as const : 'css' as const;
      return {
        request: { type: 'format' as const, source: file.content, parser },
        onResult: (res: PrettierResponse) => {
          if (res.type === 'error') {
            warnings.push(`Prettier error on ${file.path}: ${res.message}`);
            filesSkipped++;
          } else {
            if (res.changed) {
              findings.push({
                file: file.path,
                line: null,
                severity: 'warning',
                ruleId: 'prettier/format',
                message: 'File is not formatted according to Prettier rules',
              });
            }
            filesScanned++;
          }
          if (file.scanner === 'prettier-html') done['prettier-html']++;
          else done['prettier-css']++;
          onProgress({ ...done }, { ...total });
        },
      };
    });
    await runPool<PrettierReq, PrettierResponse>(makePrettierWorker, POOL_SIZE, jobs);
  }

  return {
    filesScanned,
    filesSkipped,
    totalFiles: files.length,
    findings,
    elapsedMs: Math.round(performance.now() - start),
    warnings,
  };
}
